#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist
rm -rf .built
mkdir -p .built

echo "build src -> .built .."
./node_modules/.bin/lsc -cb --no-header -o .built src

cat .built/head.js > dist/node.js
cat .built/index.js >> dist/node.js
cat .built/bundle.js >> dist/node.js
cat .built/foot.js >> dist/node.js

echo "(function(){" > dist/index.js
cat .built/index.js >> dist/index.js
cat .built/foot.js >> dist/index.js
echo "}())" >> dist/index.js

echo "(function(){" > dist/bundle.js
cat .built/index.js >> dist/bundle.js
cat .built/bundle.js >> dist/bundle.js
cat .built/foot.js >> dist/bundle.js
echo "}())" >> dist/bundle.js

echo "minify dist/index.js -> index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "minify dist/bundle.js -> bundle.min.js ..."
./node_modules/.bin/uglifyjs dist/bundle.js -m -c > dist/bundle.min.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/csscope/dev/
mkdir -p web/static/assets/lib/@plotdb/csscope/dev/
cp -R dist/* web/static/assets/lib/@plotdb/csscope/dev/

rm -rf .built
echo "done."
