#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building csscope.ls -> csscope.js ..."
npx lsc -cp src/csscope.ls > dist/csscope.js
echo "minify csscope.js -> csscope.min.js ..."
npx uglifyjs dist/csscope.js > dist/csscope.min.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/csscope/dev/
mkdir -p web/static/assets/lib/csscope/dev/
cp -R dist/* web/static/assets/lib/csscope/dev/
